server:
  port: 8085

spring:
  profiles:
    active: E0

---
## E0
spring:
  config:
    activate:
      on-profile: E0

  datasource:
    url: jdbc:mariadb://localhost:3316/mysql
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: 'true'


---
## E1 (TEST)
spring:
  config:
    activate:
      on-profile: E1

  datasource:
    url: jdbc:mariadb://3.14.200.57:3306/arun
    username: arun
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: create-update
      format_sql: 'true'